### ISSUE TITLE
Please replace .png with .svg icons

### ISSUE THREAD

**Issue by sphh** [friedPotat0/Spam-Scores#19]
**Is your feature request related to a problem? Please describe.**
On hi-res screens, the icons indicating the spam score becomes somewhat fuzzy:
![Screenshot from 2021-04-01 19-54-59](https://user-images.githubusercontent.com/4856462/113334768-9ba6e580-9313-11eb-9bb3-ac1a9e4f8a20.png)
Please compare it to the star, which is crisp.

**Describe the solution you'd like**
Replacing the icon with a .svg file should keep scaling problems at bay.

**Additional context**
The `Show InOut` add-on had a similar problem which was sorted by replacing the icon with a .svg file.

**Comment by friedPotat0** [comment]
That's right. I noticed that too and would have liked to solve it with proper vector graphics. However, I can't find any documentation on the integration of SVGs in custom columns integrated in MailExtensions. I also took a look at the latest version of the Show InOut add-on mentioned above, but it seems like they use PNG files for the column icons, too. Maybe I can slightly increase the resolution of the current PNGs.

I don't know why the documentation for these MailExtensions is so weak. You can hardly find any information about specific problems and have to collect everything from other add-ons.

I will definitely take a closer look at the resolution problem of the icons.

**Comment by sphh** [comment]
So Günter has not published it yet.

Here is the adapted `showInOUt.css` file:
```css
/* ..... inout column ..... */

treecol.inoutColumnHeader {
  list-style-image: url("correspondents-col.svg");
}

/* Using indicators */
treechildren::-moz-tree-image(sio_inoutCol, out) {
  list-style-image: url("out.svg");
}
treechildren::-moz-tree-image(sio_inoutCol, to_me) {
  list-style-image: url("to_me.svg");
}
treechildren::-moz-tree-image(sio_inoutCol, to_others) {
  list-style-image: url("to_others.svg");
}
treechildren::-moz-tree-image(sio_inoutCol, to_list) {
  list-style-image: url("to_list.svg");
}
/* end indicators*/
/* revert to old icons:
treechildren::-moz-tree-image(sio_inoutCol) {
  list-style-image: url("skin/inout.png");
}
*/
```
and the .svg is a 16×16pixel .svg file. Does this help?
